apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-api
  labels:
    app.kubernetes.io/name: etos-api
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-api
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-api
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: etos-api
      containers:
        - name: etos-api
          image: ghcr.io/eiffel-community/etos-api:a1acf6b2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
