apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: etos-api
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: logarea
  name: etos-logarea
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-api
      app.kubernetes.io/component: logarea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-api
        app.kubernetes.io/component: logarea
    spec:
      serviceAccountName: etos-logarea
      containers:
        - name: etos-logarea
          image: registry.nordix.org/eiffel/etos-logarea:f9078530
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_HOST
              value: 0.0.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /logarea/v1alpha/selftest/ping
              port: http
          readinessProbe:
            httpGet:
              path: /logarea/v1alpha/selftest/ping
              port: http
