apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: etos-api
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: executionspace
  name: etos-executionspace
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-api
      app.kubernetes.io/component: executionspace
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-api
        app.kubernetes.io/component: executionspace
    spec:
      serviceAccountName: etos-executionspace
      containers:
        - name: etos-executionspace
          image: registry.nordix.org/eiffel/etos-executionspace:672f982e
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: etos-executionspace
          env:
            - name: SERVICE_HOST
              value: 0.0.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1alpha/selftest/ping
              port: http
          readinessProbe:
            httpGet:
              path: /v1alpha/selftest/ping
              port: http
